//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class AlumniUser
    {
        public int AlumniUserID { get; set; }
        public int SalutationID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string UserDOB { get; set; }
        public string PlaceOfBirth { get; set; }
        public int GenderID { get; set; }
        public int NationalityID { get; set; }
        public int MaritalStatusID { get; set; }
        public string UserCNIC { get; set; }
        public string PassportNo { get; set; }
        public string PassportExpiryDate { get; set; }
        public string PTCLNO { get; set; }
        public string CellNo { get; set; }
        public string Email { get; set; }
        public string AlternateEmail { get; set; }
        public string GuardianName { get; set; }
        public int RelationTypeID { get; set; }
        public string GuardianCNIC { get; set; }
        public string Picture { get; set; }
        public int CountryID { get; set; }
        public int ProvinceID { get; set; }
        public int CityID { get; set; }
        public string PresentAddress { get; set; }
        public string PermanentAddress { get; set; }
        public int ReligionID { get; set; }
        public Nullable<int> CurrentOccupationID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }

        public HttpPostedFileBase ProfilePicture { get; set; }
    }

    public class AlumniUserViewModel
    {
        public List<AlumniUser> AlumniUsers { get; set; }
        public AlumniUser SelectedAlumniUsers { get; set; }

        public string DisplayMode { get; set; }
    }
}
