//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class AlumniUserResume
    {
        public int AlumniUserResumeID { get; set; }
        public Nullable<int> AlumniUserID { get; set; }
        public string ResumeDocumentPath { get; set; }

        public HttpPostedFileBase UploadFiles { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }

    public class AlumniUserResumeViewModel
    {
        public List<AlumniUserResume> AlumniUserResumes { get; set; }
        public AlumniUserResume SelectedAlumniUserResumes { get; set; }

        public string DisplayMode { get; set; }
    }
}
