//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AlumniUserCareer
    {
        public int AlumniUserCareerID { get; set; }
        public Nullable<int> AlumniUserID { get; set; }
        public string CareerTitle { get; set; }
        public string CareerDiscription { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> LastDateApply { get; set; }
        public Nullable<int> SalaryFrom { get; set; }
        public Nullable<int> SalaryTo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
    public class AlumniUserCareerViewModel
    {
        public List<AlumniUserCareer> AlumniUserCareers { get; set; }
        public AlumniUserCareer SelectedAlumniUserCareers { get; set; }

        public string DisplayMode { get; set; }
    }
}
