//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumniUserNew
    {
        public int AlumniUserNewsID { get; set; }
        public Nullable<int> AlumniUserID { get; set; }
        public string NewsTitle { get; set; }
        public string NewsContent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }

    public class AlumniUserNewViewModel
    {
        public List<AlumniUserNew> AlumniUserNews { get; set; }
        public AlumniUserNew SelectedAlumniUserNews { get; set; }

        public string DisplayMode { get; set; }
    }
}
