//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class AlumniUserPhoto
    {
        public int AlumniUserPhotoID { get; set; }
        public Nullable<int> AlumniUserID { get; set; }
        public string PhotoPath { get; set; }
        public HttpPostedFileBase UploadFiles { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }


    public class AlumniUserPhotoViewModel
    {
        public List<AlumniUserPhoto> AlumniUserPhotos { get; set; }
        public AlumniUserPhoto SelectedAlumniUserPhotos { get; set; }

        public string DisplayMode { get; set; }
    }
}
