//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumniUserBlog
    {
        public int AlumniUserBlogID { get; set; }
        public Nullable<int> AlumniUserID { get; set; }
        public string BlogTitle { get; set; }
        public string BlogContent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
    public class AlumniUserBlogViewModel
    {
        public List<AlumniUserBlog> AlumniUserBlogs { get; set; }
        public AlumniUserBlog SelectedAlumniUserBlogs { get; set; }

        public string DisplayMode { get; set; }
    }
}
