//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumniEducationExpo
    {
        public int AlumniEducationExpoID { get; set; }
        public Nullable<int> AlumniUserID { get; set; }
        public string EducationExpoTitle { get; set; }
        public string EducationExpoDetails { get; set; }
        public string EducationExpoLocation { get; set; }
        public Nullable<System.DateTime> EducationExpoStartDateTime { get; set; }
        public Nullable<System.DateTime> EducationExpoEndDateTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }

    public class AlumniEducationExpoViewModel
    {
        public List<AlumniEducationExpo> AlumniEducationExpos { get; set; }
        public AlumniEducationExpo SelectedAlumniEducationExpos { get; set; }

        public string DisplayMode { get; set; }
    }
}
