//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlumniReunionsDinner
    {
        public int AlumniReunionsDinnerID { get; set; }
        public Nullable<int> AlumniUserID { get; set; }
        public string ReunionsDinnerTitle { get; set; }
        public string ReunionsDinnerDetails { get; set; }
        public string ReunionsDinnerLocation { get; set; }
        public Nullable<System.DateTime> ReunionsDinnerStartDateTime { get; set; }
        public Nullable<System.DateTime> ReunionsDinnerEndDateTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }

    public class AlumniReunionsDinnerViewModel
    {
        public List<AlumniReunionsDinner> AlumniReunionsDinners { get; set; }
        public AlumniReunionsDinner SelectedAlumniReunionsDinners { get; set; }

        public string DisplayMode { get; set; }
    }
}
