//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class ApplicantUpload
    {
        public int ApplicantUploadID { get; set; }
        public string FormNo { get; set; }
        public string UploadPath { get; set; }

        [Display(Name = "Document Name")]
        public string DocumentName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IsActive { get; set; }
        [Display(Name = "Upload File")]
        public HttpPostedFileBase ApplicantUploadFile { get; set; }
    }

    public class ApplicantUploadViewModel
    {
        public List<ApplicantUpload> ApplicantUploads { get; set; }
        public ApplicantUpload SelectedApplicantUpload { get; set; }
        public string DisplayMode { get; set; }
    }
}
