//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class ApplicantQualification
    {
        public int AppQualiID { get; set; }
        [Display(Name = "Degree")]
        public int DegreeID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Roll #")]
        public string RollNO { get; set; }
        [Display(Name = "Registration #")]
        public string RegNo { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Year")]
        public int YearQualification { get; set; }
        [Display(Name = "City")]
        public string InstituteCity { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Total Marks/CGPA")]
        public double TotalMarks { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Obtained Marks/CGPA")]
        public double ObtainedMarks { get; set; }
        public Nullable<decimal> Percentage { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Form #")]
        public string FormNo { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }
        [Display(Name = "Institute")]
        public Nullable<int> InstituteID { get; set; }
        [Display(Name = "Document")]
        public string DegreeDocument { get; set; }
        [Display(Name = "Upload Document")]
        public HttpPostedFileBase UploadDocument { get; set; }

        public virtual Applicant Applicant { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual Institute Institute { get; set; }
    }
    public class ApplicantQualificationViewModel
    {
        public List<ApplicantQualification> ApplicantQualifications { get; set; }
        public ApplicantQualification SelectedApplicantQualification { get; set; }
        public string DisplayMode { get; set; }
    }
}
