//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bank_Account
    {
        public int Account_ID { get; set; }
        public string Account_No { get; set; }
        public int Branch_Id { get; set; }
        public string Bank_E_Code { get; set; }
        public Nullable<int> Bank_E_ID { get; set; }
        public Nullable<int> For_Commodity_ID { get; set; }
        public string Purpose { get; set; }
        public string Account_Type { get; set; }
        public Nullable<decimal> OD_Limit { get; set; }
        public Nullable<int> Compnay_id { get; set; }
        public string E_Code { get; set; }
        public string Description { get; set; }
        public Nullable<int> Financial_Company_Branch_ID { get; set; }
        public Nullable<int> Account_Access { get; set; }
        public Nullable<int> BankId { get; set; }
        public string Bank_Branch_Name { get; set; }
    }
}
