//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BatchProgramSemester
    {
        public int BatchProgramSemesterID { get; set; }
        [Display(Name = "Program")]
        public int BatchProgramID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Semester #")]
        public int YearSemesterNo { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }
        public int BatchID { get; set; }
        
        public virtual BatchProgram BatchProgram { get; set; }
        public virtual Semester Semester { get; set; }
    }

    public class BatchProgramSemesterViewModel
    {
        public List<BatchProgramSemester> BatchProgramSemesters { get; set; }
        public BatchProgramSemester SelectedBatchProgramSemester { get; set; }
        public string DisplayMode { get; set; }
    }
}
