//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BatchProgramCourse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchProgramCourse()
        {
            this.StudentBatchProgramCourses = new HashSet<StudentBatchProgramCourse>();
            this.TeachersCourseAllocations = new HashSet<TeachersCourseAllocation>();
        }

        [Display(Name = "ProgramCourseID")]
        public int ProgramCourseID { get; set; }

        [Display(Name = "Program")]
        public int BatchProgramID { get; set; }
        [Display(Name = "Course")]
        public int CourseID { get; set; }
        [Display(Name = "Year/Semester #")]
        public int YearSemesterNo { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }
        [Display(Name = "Course Type")]
        public Nullable<int> CourseTypeID { get; set; }
    
        public virtual BatchProgram BatchProgram { get; set; }
        public virtual Course Course { get; set; }
        public virtual CourseType CourseType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentBatchProgramCourse> StudentBatchProgramCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeachersCourseAllocation> TeachersCourseAllocations { get; set; }
    }

    public class BatchProgramCourseViewModel
    {
        public List<BatchProgramCourse> BatchProgramCourses { get; set; }
        public BatchProgramCourse SelectedBatchProgramCourse { get; set; }
        public string DisplayMode { get; set; }
    }
}
