//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class BeliTrust
    {
        public int BeliTrustID { get; set; }

        [Display(Name = "Form #")]
        public string FormNo { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "Father's Name")]
        public string FatherName { get; set; }

        [Display(Name = "Date Of Birth")]
        public System.DateTime ApplicantDOB { get; set; }

        [Display(Name = "Place Of Birth")]
        public string PlaceOfBirth { get; set; }

        [Display(Name = "CNIC #")]
        public string ACNIC { get; set; }

        public string PTCLNO { get; set; }

        [Display(Name = "Mobile #")]
        public string CellNo { get; set; }

        [Display(Name = "Email Address")]
        public string Email { get; set; }

        public string AlternateEmail { get; set; }

        [Display(Name = "Guardian's Name")]
        public string GuardianName { get; set; }

        [Display(Name = "Guardian's CNIC #")]
        public string GuardianCNIC { get; set; }

        public string Picture { get; set; }

        [Display(Name = "Residential Address")]
        public string PresentAddress { get; set; }

        public string PermanentAddress { get; set; }

        [Display(Name = "Name Of Organization")]
        public string NameOfOrganization { get; set; }

        [Display(Name = "Designation")]
        public string DesignationName { get; set; }

        [Display(Name = "Date Of Retirement")]
        public string DateOfRetirement { get; set; }

        [Display(Name = "Retired Position")]
        public string RetiredPosition { get; set; }

        [Display(Name = "Retired Organization")]
        public string RetiredOrganization { get; set; }

        [Display(Name = "Last Drawn Gross Salary")]
        public string RetiredLastDrawnGrossSalary { get; set; }

        [Display(Name = "Nature Of Business")]
        public string NatureOfBusiness { get; set; }

        [Display(Name = "Monthly Income")]
        public string MonthlyIncomeOrg { get; set; }

        [Display(Name = "Nature Of Source")]
        public string NatureOfSource { get; set; }

        [Display(Name = "Monthly Income Source")]
        public string MonthlyIncomeSource { get; set; }

        [Display(Name = "Type Of Residence")]
        public string TypeOfResidence { get; set; }

        [Display(Name = "Text")]
        public string ResidenceText { get; set; }

        [Display(Name = "Monthly Rent (in case of rented accomodation")]
        public string MonthlyRent { get; set; }

        [Display(Name = "Total Tuition Fee")]
        public string TotalTuitionFee { get; set; }

        [Display(Name = "Request For Concession")]
        public string RequestForConcession { get; set; }

        [Display(Name = "Remarks By Principal")]
        public string RemarksByPrincipal { get; set; }

        [Display(Name = "Remarks By HOD")]
        public string RemarksByHOD { get; set; }

        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }

        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }

        [Display(Name = "Is Active")]
        public string IsActive { get; set; }

        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }

        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        [Display(Name = "Monthly Salary")]
        public string MonthlySalary { get; set; }

        [Display(Name = "Monthly Income Business")]
        public string MonthlyIncomeBus { get; set; }

        [Display(Name = "Salutation")]
        public string SalutationName { get; set; }

        [Display(Name = "Status")]
        public string StatusName { get; set; }

        [Display(Name = "Marital Status")]
        public string MaritalStatusName { get; set; }

        [Display(Name = "Gender")]
        public string GenderName { get; set; }

        [Display(Name = "Relationship with Applicant")]
        public string RelationTypeName { get; set; }
        public Nullable<int> BeliTrustCategoryID { get; set; }
    }
}
