//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BeliTrustAffidavit
    {
        public int BeliTrustAffidavitID { get; set; }
        
        [Display(Name = "Form #")]
        public string FormNo { get; set; }

        [Display(Name = "Affidavit of")]
        public string ApplicantName { get; set; }

        [Display(Name = "Son/Daughter of")]
        public string FatherName { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Cast")]
        public string CastName { get; set; }

        [Display(Name = "Resident of")]
        public string Address { get; set; }

        [Display(Name = "Family Monthly Income")]
        public string FamilyIncome { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Name")]
        public string DeponentName { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Father/Guardian's Name")]
        public string DeponentFatherName { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "CNIC #")]
        public string DeponentCNIC { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Address")]
        public string DeponentAddress { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Name")]
        public string Witness1Name { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Father's Name")]
        public string Witness1FatherName { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "CNIC #")]
        public string Witness1CNIC { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Address")]
        public string Witness1Address { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Name")]
        public string Witness2Name { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Father's Name")]
        public string Witness2FatherName { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "CNIC #")]
        public string Witness2CNIC { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Address")]
        public string Witness2Address { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "R/O")]
        public string ReverseOf { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Deponent Declares at")]
        public string DeponentDeclareAt { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Deponent Declares on")]
        public string DeponentDeclareOn { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "Deponent Declares Oath")]
        public string DeponentDeclareOnOath { get; set; }
       
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }

        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }

        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }

        [Display(Name = "Modified By")]
        public Nullable<int> Modifiedby { get; set; }

        [Display(Name = "Is Active")]
        public string IsActive { get; set; }

        [Required(ErrorMessage = "Required")]
        [Display(Name = "CNIC #")]
        public string ACNIC { get; set; }
    }
}
