//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampusSetting
    {
        public int CampusSettingID { get; set; }
        public string CampusName { get; set; }
        public string CampusLogo { get; set; }
        public string CampusBackground { get; set; }
        public string CompanyLogo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string LogoWidth { get; set; }
        public string LogoHeight { get; set; }
        public string MarginTop { get; set; }
        public string CampusTitle { get; set; }
        public string MarginLeftTitle { get; set; }
        public int Hospital_ID { get; set; }
        public string EligibilityPercentage { get; set; }
        public string CampusAddress { get; set; }
        public string UniversityCampusName { get; set; }
		public string LayoutName { get; set; }
		public string UniversityName { get; set; }

        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string MobileNumber1 { get; set; }
        public string MobileNumber2 { get; set; }
        public string MobileNumber3 { get; set; }
        public string UniversityEmail { get; set; }
        public string CampusEmail { get; set; }
        public string QueryEmail { get; set; }
		public string Extension1 { get; set; }
		public string Extension2 { get; set; }
		public string Extension3 { get; set; }
    }
}
