//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChallanService
    {
        public int ChallanServiceID { get; set; }
        public Nullable<int> ChallanID { get; set; }
        public int CollegeServiceID { get; set; }
        public Nullable<int> Amount { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual Challan Challan { get; set; }
        public virtual CollegeService CollegeService { get; set; }
    }
}
