//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class CollegeService
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollegeService()
        {
            this.ChallanServices = new HashSet<ChallanService>();
        }

        [Display(Name = "Service ID")]
        public int CollegeServiceID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Service Name")]
        public string CollegeServiceName { get; set; }
        [Display(Name = "Amount")]
        public Nullable<decimal> Amount { get; set; }
        [Display(Name = "Is Effect Program Fee")]
        public string IsEffectProgramFee { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }
        [Display(Name = "Financial Head")]
        public string E_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChallanService> ChallanServices { get; set; }
    }

    public class CollegeServicesViewModel
    {
        public List<CollegeService> CollegeServices { get; set; }
        public CollegeService SelectedCollegeService { get; set; }
        public string DisplayMode { get; set; }
    }
}
