//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.BatchProgramCourses = new HashSet<BatchProgramCourse>();
            this.StudentBatchProgramCourses = new HashSet<StudentBatchProgramCourse>();
        }

        [Display(Name = "Course Name")]
        public int CourseID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Course Name")]
        public string CourseName { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Course Code")]
        public string CourseCode { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Credit Hours")]
        public int CreditHours { get; set; }
        [Display(Name = "Description")]
        public string CourseDescription { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchProgramCourse> BatchProgramCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentBatchProgramCourse> StudentBatchProgramCourses { get; set; }
    }

    public class CoursesViewModel
    {
        public List<Course> Courses { get; set; }
        public Course SelectedCourse { get; set; }
        public string DisplayMode { get; set; }
    }
}
