//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class CourseType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseType()
        {
            this.BatchProgramCourses = new HashSet<BatchProgramCourse>();
        }

        [Display(Name = "Course Type ID")]
        public int CourseTypeID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Course Type")]
        public string CourseTypeName { get; set; }
        [Display(Name = "Description")]
        public string CourseTypeDescription { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchProgramCourse> BatchProgramCourses { get; set; }
    }
    public class CourseTypesViewModel
    {
        public List<CourseType> CourseTypes { get; set; }
        public CourseType SelectedCourseType { get; set; }
        public string DisplayMode { get; set; }
    }

}
