//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DepositType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepositType()
        {
            this.FormSaleDetails = new HashSet<FormSaleDetail>();
        }

        [Display(Name = "Deposit Type ID")]
        public int DepositTypeID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Deposit Type")]
        public string DepositTypeName { get; set; }
        [Display(Name = "Description")]
        public string DepositTypeDesc { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormSaleDetail> FormSaleDetails { get; set; }
    }

    public class DepositTypesViewModel
    {
        public List<DepositType> DepositTypes { get; set; }
        public DepositType SelectedDepositType { get; set; }
        public string DisplayMode { get; set; }
    }
}
