//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DisciplineType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisciplineType()
        {
            this.DisciplineCategories = new HashSet<DisciplineCategory>();
        }
    
        public int DisciplineTypeID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Discipline Type")]
        public string DisciplineTypeName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DisciplineCategory> DisciplineCategories { get; set; }
    }
    
    public class DisciplineTypeViewModel
    {
        public List<DisciplineType> DisciplineTypes { get; set; }
        public DisciplineType SelectedDisciplineType { get; set; }
        public string DisplayMode { get; set; }
    }
}
