//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Discipline
    {
        public int DisciplineID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Discipline Date")]
        [DataType(DataType.Date)]
        public string DisciplineDate { get; set; }
        public string Description { get; set; }
        [Display(Name = "Student")]
        public Nullable<int> StudentID { get; set; }
        [Display(Name = "Discipline Category")]
        public Nullable<int> DisciplineCategoryID { get; set; }
        [Display(Name = "Discipline Committed")]
        public Nullable<int> DisciplineCommittedID { get; set; }
        [Display(Name = "Status")]
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }

        public virtual DisciplineCategory DisciplineCategory { get; set; }
        public virtual DisciplineCommitted DisciplineCommitted { get; set; }
        public virtual Status Status { get; set; }
        public virtual Student Student { get; set; }
    }

    public class DisciplineViewModel
    {
        public List<Discipline> Disciplines { get; set; }
        public Discipline SelectedDiscipline { get; set; }
        public string DisplayMode { get; set; }
    }
}
