//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DisciplineCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DisciplineCategory()
        {
            this.Disciplines = new HashSet<Discipline>();
        }

        public int DisciplineCategoryID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Discipline Category")]
        public string DisciplineCategoryName { get; set; }
        [Display(Name = "Description")]
        public string Description { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }
        [Display(Name = "Point (Weightage)")]
        public string PointWeightage { get; set; }
        [Display(Name = "Penalty/Punishment")]
        public string Punishment { get; set; }
        [Display(Name = "Discipline Type")]
        public Nullable<int> DisciplineTypeID { get; set; }
        [Display(Name = "Discipline Severity Level")]
        public Nullable<int> DisciplineSeverityLevelID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discipline> Disciplines { get; set; }
        public virtual DisciplineSeverityLevel DisciplineSeverityLevel { get; set; }
        public virtual DisciplineType DisciplineType { get; set; }
    }

    public class DisciplineCategoryViewModel
    {
        public List<DisciplineCategory> DisciplineCategories { get; set; }
        public DisciplineCategory SelectedDisciplineCategory { get; set; }
        public string DisplayMode { get; set; }
    }
}
