//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntryTest
    {
        public int EntryTestID { get; set; }
        public string EntryTestName { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
		public Nullable<int> DegreeID { get; set; }
        public Nullable<int> EntryTestTotalMarks { get; set; }

    }

    public class EntryTestViewModel
    {
        public List<EntryTest> EntryTests { get; set; }
        public EntryTest SelectedEntryTests { get; set; }
        public string DisplayMode { get; set; }
    }
}
