//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamSubjectMarkSheet
    {
        public int ExamSubjectMarkSheetID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> BatchProgramID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string FormNo { get; set; }
        public Nullable<int> CourseID { get; set; }
        public string ObtainedMarks { get; set; }
        public string TotalMarks { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IsActive { get; set; }
		public Nullable<int> YearSemesterNo { get; set; }
    }
}
