//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ExamID { get; set; }
        public string ExamTitle { get; set; }
        public Nullable<int> ExamSeasonID { get; set; }
        public Nullable<int> ExamTermID { get; set; }
        public string ExamStartDate { get; set; }
        public string ExamEndDate { get; set; }
        public Nullable<int> IsDateSheetApproved { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }

    public class ExamsViewModel
    {
        public List<Exam> Exams { get; set; }
        public Exam SelectedExam { get; set; }
        public string DisplayMode { get; set; }
    }

}
