//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamStudentSubjectChangeGradeForm
    {
        public int ExamStudentSubjectChangeGradeFormID { get; set; }
        public Nullable<int> ExamStudentSubjectMarkID { get; set; }
        public Nullable<int> ExamStudentSubjectMarkDetailID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> ProgramCourseID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> StudentPresentStatusID { get; set; }
        public Nullable<int> ExamStudentSubjectMarkTypeID { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public Nullable<decimal> ObtainOldMarks { get; set; }
        public Nullable<decimal> ObtainNewMarks { get; set; }
        public Nullable<int> YearSemesterNo { get; set; }
        public string Reason { get; set; }
        public Nullable<int> IsTeacherApproveOrDisapprove { get; set; }
        public Nullable<System.DateTime> TeacherApproveOrDisapproveDate { get; set; }
        public Nullable<int> IsHodApproveOrDisapprove { get; set; }
        public Nullable<System.DateTime> HodApproveOrDisapproveDate { get; set; }
        public Nullable<int> IsDeanApproveOrDisapprove { get; set; }
        public Nullable<int> DeanApproveOrDisapproveDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
