//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamStudentSubjectMarkDetail
    {
        public int ExamStudentSubjectMarkDetailID { get; set; }
        public int ExamStudentSubjectMarkID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> ProgramCourseID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ExamStudentSubjectMarkTypeID { get; set; }
        public Nullable<decimal> TotalMarks { get; set; }
        public Nullable<decimal> ObtainMarks { get; set; }
        public Nullable<int> StudentPresentStatusID { get; set; }
        public Nullable<int> IsTeacherSubmitted { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
