//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyMember
    {
        public int FamilyMemberID { get; set; }
        public string FormNo { get; set; }
        public string FamilyMemberName { get; set; }
        public string FamilyMemberAge { get; set; }
        public string RelationWithStudent { get; set; }
        public string MaritalStatus { get; set; }
        public string MonthlyEducationExpense { get; set; }
        public string MedicalExpense { get; set; }
        public string TotalFamilyMember { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public string IsActive { get; set; }
    }
}
