//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class FormSaleDetail
    {
        [Display(Name = "Form ID")]
        public int FormID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Form #")]
        public string FormNo { get; set; }
        [Display(Name = "Form Type")]
        public Nullable<int> FormTypeID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Form Price")]
        public string FormPrice { get; set; }
        [Display(Name = "Description")]
        public string FormDescription { get; set; }
        [Display(Name = "Deposit Type")]
        public Nullable<int> DepositTypeID { get; set; }
        [Display(Name = "Batch Program")]
        public Nullable<int> BatchProgramID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Applicant Name")]
        public string ApplicantName { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Father/Husband")]
        public string FatherName { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Phone #")]
        public string PhoneNo { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "CNIC")]
        public string CNIC { get; set; }
        [Display(Name = "Deposit Slip #")]
        public string DepositSlipNo { get; set; }
        [Display(Name = "Date")]
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        [Display(Name = "Bank Account")]
        public Nullable<int> AccountID { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        public Nullable<int> Voucher_Trans_ID { get; set; }
        public string IsReceived { get; set; }
        [Display(Name = "Date")]
        public Nullable<System.DateTime> ReceiveDate { get; set; }
    
        public virtual BatchProgram BatchProgram { get; set; }
        public virtual DepositType DepositType { get; set; }
        public virtual FormType FormType { get; set; }
    }

    public class FormSaleDetailsViewModel
    {
        public List<FormSaleDetail> FormSaleDetails { get; set; }
        public FormSaleDetail SelectedFormSaleDetail { get; set; }
        public string DisplayMode { get; set; }
    }
}
