//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class FormSaleDetail
    {
        [Display(Name = "Form ID")]
        public int FormID { get; set; }
        
        [Display(Name = "Form #")]
        public string FormNo { get; set; }
        [Display(Name = "Form Type")]
        public Nullable<int> FormTypeID { get; set; }
        
        [Display(Name = "Application Processing Fee")]
        public string FormPrice { get; set; }
        [Display(Name = "Description")]
        public string FormDescription { get; set; }
        [Display(Name = "Deposit Type")]
        public Nullable<int> DepositTypeID { get; set; }
        [Display(Name = "Program")]
        public Nullable<int> BatchProgramID { get; set; }
        
        [Display(Name = "Applicant Name")]
        public string ApplicantName { get; set; }
        
        [Display(Name = "Father/Husband")]
        public string FatherName { get; set; }
        
        [Display(Name = "Phone #")]
        public string PhoneNo { get; set; }
        
        [Display(Name = "CNIC/Passport")]
        public string CNIC { get; set; }
        [Display(Name = "Draft #")]
        public string DepositSlipNo { get; set; }
        [Display(Name = "Date")]
        public string PurchaseDate { get; set; }
        [Display(Name = "Bank Account")]
        public Nullable<int> AccountID { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        public Nullable<int> Voucher_Trans_ID { get; set; }
        public string IsReceived { get; set; }
        [Display(Name = "Receive Date")]
        public string ReceiveDate { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Test Type")]
        public Nullable<int> DegreeID { get; set; }

        [Display(Name = "Waive Off/Discount")]
        public string Wavier_Discount { get; set; }

        [Display(Name = "Program Preference 1")]
        public Nullable<int> BatchProgramID1 { get; set; }
        [Display(Name = "Program Preference 2")]
        public Nullable<int> BatchProgramID2 { get; set; }
        [Display(Name = "Program Preference 3")]
        public Nullable<int> BatchProgramID3 { get; set; }
        public Nullable<int> LevelID { get; set; }

        public virtual BatchProgram BatchProgram { get; set; }
        public virtual DepositType DepositType { get; set; }
        public virtual FormType FormType { get; set; }
    }

    //public class FormSaleDetailsViewModel
    //{
    //    public List<FormSaleDetail> FormSaleDetails { get; set; }
    //    public FormSaleDetail SelectedFormSaleDetail { get; set; }
    //    public string DisplayMode { get; set; }
    //}
}
