//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class GeneralSetting
    {
        public int GeneralSettingID { get; set; }
        [Display(Name = "Application Fee")]
        public string ProspectusFee { get; set; }
        [Display(Name = "Bachelor Percentage")]
        public string BachelorPercentage { get; set; }
        [Display(Name = "Masters Percentage")]
        public string MastersPercentage { get; set; }
        [Display(Name = "Phd Percentage")]
        public string PhdPercentage { get; set; }
        [Display(Name = "Entry Test Date")]
        public Nullable<System.DateTime> EntryTestDate { get; set; }
        [Display(Name = "Entry Test Result Date")]
        public Nullable<System.DateTime> EntryTestResultDate { get; set; }
        [Display(Name = "GAT Percentage")]
        public string GATPercentage { get; set; }
        [Display(Name = "NAT Percentage")]
        public string NATPercentage { get; set; }
        [Display(Name = "First Merit List Date")]
        public Nullable<System.DateTime> FirstMeritListDate { get; set; }
        [Display(Name = "Second Merit List Date")]
        public Nullable<System.DateTime> SecondMeritListDate { get; set; }
        [Display(Name = "Third Merit List Date")]
        public Nullable<System.DateTime> ThirdMeritListDate { get; set; }
        [Display(Name = "Fourth Merit List Date")]
        public Nullable<System.DateTime> FourthMeritListDate { get; set; }
        [Display(Name = "Sending Offer Letter Date")]
        public Nullable<System.DateTime> SendingOfferLetterDate { get; set; }
        [Display(Name = "Orientation Date")]
        public Nullable<System.DateTime> OrientationDate { get; set; }
        [Display(Name = "Bachelor Max Credit Hours")]
        public string BachelorMaxCreditHours { get; set; }
        [Display(Name = "Masters Max Credit Hours")]
        public string MastersMaxCreditHours { get; set; }
        [Display(Name = "MPhil Max Credit Hours")]
        public string MPhilMaxCreditHours { get; set; }
        [Display(Name = "Add Drop Dead line Date")]
        public Nullable<System.DateTime> AddDropDeadlineDate { get; set; }
        [Display(Name = "Withdrawal Subject Date")]
        public Nullable<System.DateTime> WithdrawalSubjectDate { get; set; }
        [Display(Name = "Entry Test Percentage")]
        public string EntryTestPercentage { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }
    }

    public class GeneralSettingViewModel
    {
        public List<GeneralSetting> GeneralSettings { get; set; }
        public GeneralSetting SelectedGeneralSettings { get; set; }
        public string DisplayMode { get; set; }
    }
}
