//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMSQuiz
    {
        public int LMSQuizID { get; set; }
        public string QuizTitle { get; set; }
        public Nullable<int> LMSWeekDetailID { get; set; }
        public string QuizTimeInterval { get; set; }
        public Nullable<int> NoOfTries { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }

    public class LMSQuizViewModel
    {
        public List<LMSQuiz> LMSQuizs { get; set; }
        public LMSQuiz SelectedLMSQuizs { get; set; }

        public string DisplayMode { get; set; }
    }
}
