//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMSQuizIQuestion
    {
        public int LMSQuizIQuestionD { get; set; }
        public int LMSQuizID { get; set; }
        public Nullable<int> LMSQuestionTypeID { get; set; }
        public Nullable<bool> IsNegativeMarking { get; set; }
        public string AskedQuestion { get; set; }
        public Nullable<decimal> QuestionMarks { get; set; }
        public string QuestionMCQ1 { get; set; }
        public Nullable<bool> AnswerMCQ1 { get; set; }
        public string AnswerMCQTitle1 { get; set; }
        public string QuestionMCQ2 { get; set; }
        public Nullable<bool> AnswerMCQ2 { get; set; }
        public string AnswerMCQTitle2 { get; set; }
        public string QuestionMCQ3 { get; set; }
        public Nullable<bool> AnswerMCQ3 { get; set; }
        public string AnswerMCQTitle3 { get; set; }
        public string QuestionMCQ4 { get; set; }
        public Nullable<bool> AnswerMCQ4 { get; set; }
        public string AnswerMCQTitle4 { get; set; }
        public string QuestionTrueTitle { get; set; }
        public string QuestionFalseTitle { get; set; }
        public Nullable<bool> AnswerTrueFalse { get; set; }
        public string QuestionSCQ1 { get; set; }
        public Nullable<bool> AnswerSCQ1 { get; set; }
        public string AnswerSCQTitle1 { get; set; }
        public string QuestionSCQ2 { get; set; }
        public Nullable<bool> AnswerSCQ2 { get; set; }
        public string AnswerSCQTitle2 { get; set; }
        public string QuestionSCQ3 { get; set; }
        public Nullable<bool> AnswerSCQ3 { get; set; }
        public string AnswerSCQTitle3 { get; set; }
        public string QuestionSCQ4 { get; set; }
        public Nullable<bool> AnswerSCQ4 { get; set; }
        public string AnswerSCQTitle4 { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }

    public class LMSQuizIQuestionViewModel
    {
        public List<LMSQuizIQuestion> LMSQuizIQuestions { get; set; }
        public LMSQuizIQuestion SelectedLMSQuizIQuestions { get; set; }

        public string DisplayMode { get; set; }
    }
}
