//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMSWeek
    {
        public int LMSWeekID { get; set; }
        public Nullable<int> LMSSubjectLearningID { get; set; }
        public string Title { get; set; }
        public string TopicText { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IsActive { get; set; }
    }

    public class LMSWeekViewModel
    {
        public List<LMSWeek> LMSWeeks { get; set; }
        public LMSWeek SelectedLMSWeeks { get; set; }
        public LMSWeekDetailAttempt LMSWeekDetailAttemptObj { get; set; }
        public string DisplayMode { get; set; }
    }
}
