//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class LMSWeekDetail
    {
        public int LMSWeekDetailID { get; set; }
        public Nullable<int> LMSWeekID { get; set; }
        public Nullable<int> WeekListTypeID { get; set; }
        public string Title { get; set; }
        public string ContentText { get; set; }
        public string FilePath { get; set; }

        public HttpPostedFileBase UploadFiles { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IsActive { get; set; }
    }


    public class LMSWeekDetailsViewModel
    {
        public List<LMSWeekDetail> LMSWeekDetails { get; set; }
        public LMSWeekDetail SelectedLMSWeekDetails { get; set; }

        public string DisplayMode { get; set; }
    }
}
