//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LMSWeekDetailAttempt
    {
        public int LMSWeekDetailAttemptID { get; set; }
        public Nullable<int> LMSWeekDetailID { get; set; }
        public Nullable<int> LMSWeekID { get; set; }
        public Nullable<int> WeekListTypeID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public bool IsAttempt { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string IsActive { get; set; }
    }

    public class LMSWeekDetailAttemptViewModel
    {
        public List<LMSWeekDetailAttempt> LMSWeekDetailAttempts { get; set; }
        public LMSWeekDetailAttempt SelectedLMSWeekDetailAttempts { get; set; }
        public string DisplayMode { get; set; }
    }
}
