//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string UserName { get; set; }
        public string Password { get; set; }
        public int EmpID { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> MainPage_Id { get; set; }
        public int id { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public string Confirmation_Code { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> entry_emp { get; set; }
        public Nullable<bool> Branch_Access { get; set; }
        public string UserName1 { get; set; }
        public string EmpType { get; set; }
        public string Email { get; set; }
        public string MobileNumber { get; set; }
        public string CNIC { get; set; }
    }
}
