//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_log
    {
        public int id { get; set; }
        public Nullable<int> emp_ID { get; set; }
        public Nullable<System.DateTime> Log_Time { get; set; }
        public string system_IP { get; set; }
        public string Remote_Address { get; set; }
    }
}
