//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NoticeBoard
    {
        public int NoticeBoardID { get; set; }
        [Display(Name = "Title")]
        public string NoticeBoardTitle { get; set; }
        [Display(Name = "Text")]
        public string NoticeBoardText { get; set; }
        [Display(Name = "Type")]
        public Nullable<int> NoticeTypeID { get; set; }
        [Display(Name = "Faculty")]
        public Nullable<int> FacultyID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
