//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBE_BatchProgramPLOCourseCLO
    {
        public int BatchProgramPLOCourseCLOID { get; set; }
        public Nullable<int> PLOCourseCLOID { get; set; }
        public Nullable<int> BatchProgramID { get; set; }
        public Nullable<decimal> Weightage { get; set; }
    }
}
