//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Program
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Program()
        {
            this.BatchPrograms = new HashSet<BatchProgram>();
        }

        [Display(Name = "Program ID")]
        public int ProgramID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Program Code")]
        public string ProgramCode { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Program Name")]
        public string ProgramName { get; set; }
        [Display(Name = "Description")]
        public string ProgramDescription { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Semesters/Years")]
        public int SemestersYears { get; set; }
        [Display(Name = "Program Type")]
        public int ProgramTypeID { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchProgram> BatchPrograms { get; set; }
        public virtual ProgramType ProgramType { get; set; }
    }

    public class ProgramsViewModel
    {
        public List<Program> Programs { get; set; }
        public Program SelectedProgram { get; set; }
        public string DisplayMode { get; set; }
    }
}
