//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramMeritFormula
    {
        public int ProgramMeritFormulaID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public Nullable<int> MatricPercentage { get; set; }
        public Nullable<int> IntermediatePercentage { get; set; }
        public Nullable<int> GraduationPercentage { get; set; }
        public Nullable<int> PostGraduationPercentage { get; set; }
        public Nullable<int> EntryTestPercentage { get; set; }
        public Nullable<int> InterviewPercentage { get; set; }
        public Nullable<int> DrawingTestPercentage { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
