//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.TimeSlots = new HashSet<TimeSlot>();
        }

        [Display(Name = "Room ID")]
        public int RoomID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Room Name")]
        public string RoomName { get; set; }
        [Display(Name = "Description")]
        public string RoomDescription { get; set; }
        [Display(Name = "Room Type")]
        public int RoomTypeID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Room Capacity")]
        public int RoomCapacity { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSlot> TimeSlots { get; set; }
    }

    public class RoomsViewModel
    {
        public List<Room> Rooms { get; set; }
        public Room SelectedRoom { get; set; }
        public string DisplayMode { get; set; }
    }
}
