//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    public partial class ScholarshipOpportunitie
    {
        public int ScholarshipOpportunitiesID { get; set; }
        public Nullable<int> ScholarshipCatagoryID { get; set; }
        public string ScholarshipImagePath { get; set; }
        public string ScholarshipTitle { get; set; }
        public string ScholarshipDescription { get; set; }
        public string HowToQualify { get; set; }
        public string EligibilityDescription { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public HttpPostedFileBase UploadFiles { get; set; }
    }
    public class ScholarshipOpportunitieViewModel
    {
        public List<ScholarshipOpportunitie> ScholarshipOpportunities { get; set; }
        public ScholarshipOpportunitie SelectedScholarshipOpportunitie { get; set; }
        public string DisplayMode { get; set; }
    }

    
}
