//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SelectionCriteria
    {
        public int CriteriaID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Program")]
        public Nullable<int> BatchProgramID { get; set; }
        [Display(Name = "Degree")]
        public Nullable<int> DegreeID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Percentage")]
        public Nullable<double> DegreePercentage { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        public virtual BatchProgram BatchProgram { get; set; }
        public virtual Degree Degree { get; set; }
    }
}
