//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SF_StudentServiceInstallmentAdjustment
    {
        public int StudentServiceInstallmentAdjustmentID { get; set; }
        public Nullable<int> StudentServiceID { get; set; }
        public Nullable<int> CollegeServiceID { get; set; }
        public Nullable<decimal> CollegeServiceAmount { get; set; }
        public Nullable<int> YearSemesterNo { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public string IsActive { get; set; }
    }
}
