//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Disciplines = new HashSet<Discipline>();
            this.StudentBatchProgramCourses = new HashSet<StudentBatchProgramCourse>();
            this.StudentProgramEnrollments = new HashSet<StudentProgramEnrollment>();
        }

        public int StudentID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Form #")]
        public string FormNo { get; set; }
       

        public Nullable<int> AddAppID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Salutation")]
        public int SalutationID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        //[Required(ErrorMessage = "Required")]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Father Name")]
        public string FatherName { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "DOB")]
        public string StudentDOB { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Place of Birth")]
        public string PlaceOfBirth { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Gender")]
        public int GenderID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Nationality")]
        public int NationalityID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Marital Status")]
        public int MaritalStatusID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "CNIC")]
        public string ACNIC { get; set; }
        [Display(Name = "Passport #")]
        public string PassportNo { get; set; }
        [Display(Name = "Expiry Date")]
        public string PassportExpiryDate { get; set; }
        [Display(Name = "Home Phone #")]
        public string PTCLNO { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Cell #")]
        public string CellNo { get; set; }
        [Required(ErrorMessage = "Required")]
        [EmailAddress(ErrorMessage = "Invalid Email")]
        public string Email { get; set; }
        [Display(Name = "Alternate Email")]
        [EmailAddress(ErrorMessage = "Invalid Email")]
        public string AlternateEmail { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Parent/Guardian")]
        public string GuardianName { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Relation Type")]
        public int RelationTypeID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "CNIC")]
        public string GuardianCNIC { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Program")]
        public int BatchProgramID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Profile Picture")]
        public string Picture { get; set; }
        //[Required(ErrorMessage = "Required")]
        [Display(Name = "Country")]
        public int CountryID { get; set; }
        //[Required(ErrorMessage = "Required")]
        [Display(Name = "State")]
        public int ProvinceID { get; set; }
        //[Required(ErrorMessage = "Required")]
        [Display(Name = "City")]
        public int CityID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Present Address")]
        public string PresentAddress { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Permanent Address")]
        public string PermanentAddress { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Religion")]
        public int ReligionID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Current Occupation")]
        public Nullable<int> CurrentOccupationID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Status")]
        public Nullable<int> StatusID { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        [Display(Name = "Profile Picture")]
        public HttpPostedFileBase ProfilePicture { get; set; }
        [Display(Name = "Level")]
        public Nullable<int> LevelID { get; set; }
        [Display(Name = "Faculty")]
        public Nullable<int> FacultyID { get; set; }
        public Nullable<int> CurrentSemesterNo { get; set; }
        [Display(Name = "Roll #")]
        public string RollNumber { get; set; }
        [Display(Name = "Registration #")]
        public string RegistrationNo { get; set; }

        public Nullable<int> CheckForStudentProfile { get; set; } //Check of coming from Student Profile

        public virtual Applicant Applicant { get; set; }
        public virtual BatchProgram BatchProgram { get; set; }
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual CurrentOccupation CurrentOccupation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discipline> Disciplines { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual MaritalStatu MaritalStatu { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Province Province { get; set; }
        public virtual RelationType RelationType { get; set; }
        public virtual Religion Religion { get; set; }
        public virtual Salutation Salutation { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentBatchProgramCourse> StudentBatchProgramCourses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentProgramEnrollment> StudentProgramEnrollments { get; set; }
    }
}
