//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDiscountRequest
    {
        public int StudentDiscountRequestID { get; set; }
        public string FormNo { get; set; }
        public Nullable<int> StudentRequestTypeID { get; set; }
        public string RequestDescription { get; set; }
        public Nullable<int> StudentRequestStatusID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> Modifiedby { get; set; }
        public string IsActive { get; set; }
        public string DiscountPercentage { get; set; }
    }


}
