//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TeachersCourseAllocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeachersCourseAllocation()
        {
            this.TimeSlotCourseAllocations = new HashSet<TimeSlotCourseAllocation>();
        }

        [Display(Name = "TCourseAllocationID")]
        public int TCourseAllocationID { get; set; }
        [Display(Name = "Program Course")]
        public int ProgramCourseID { get; set; }
        [Display(Name = "Teacher")]
        public int TeacherID { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        public virtual BatchProgramCourse BatchProgramCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSlotCourseAllocation> TimeSlotCourseAllocations { get; set; }
    }

    public class TeachersCourseAllocationsViewModel
    {
        public List<TeachersCourseAllocation> TeachersCourseAllocations { get; set; }
        public TeachersCourseAllocation SelectedTeachersCourseAllocation { get; set; }
        public string DisplayMode { get; set; }
    }
}
