//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class TeacherUpload
    {
        public int TeacherUploadID { get; set; }
        public string TeacherUploadName { get; set; }
        public string TeacherUploadType { get; set; }
        public string SubmissonDate { get; set; }
        public string UploadPath { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> EmpID { get; set; }

        public HttpPostedFileBase TeacherUploadFile { get; set; }
    }

    public class TeacherUploadViewModel
    {
        public List<TeacherUpload> TeacherUploads { get; set; }
        public TeacherUpload SelectedTeacherUpload { get; set; }
        public string DisplayMode { get; set; }
    }
}
