//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableData
    {
        public int TimeTableDataID { get; set; }
        public Nullable<int> TimeTableMainID { get; set; }
        public Nullable<int> TimeTableSlotID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<int> ProgramCourseID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> DayID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }
}
