//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableManualTimeSlot
    {
        public int TimeTableManualTimeSlotID { get; set; }
        public Nullable<int> TimeTableSlotID { get; set; }
        public string DayName { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> DayID { get; set; }
    }
    public class tt_GetTimeTableManualTimeSlot_ResultViewModel
    {
        public List<tt_GetTimeTableManualTimeSlot_Result> tt_GetTimeTableManualTimeSlot_Results { get; set; }
        public tt_GetTimeTableManualTimeSlot_Result Selectedtt_GetTimeTableManualTimeSlot_Result { get; set; }
        public string DisplayMode { get; set; }
    }
}
