//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TimeSlotCourseAllocation
    {
        public int TimeSlotCourseAllocationID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Time Slot")]
        public Nullable<int> TimeSlotID { get; set; }
        [Required(ErrorMessage = "Required")]
        [Display(Name = "Course")]
        public Nullable<int> TCourseAllocationID { get; set; }
        [Display(Name = "Created On")]
        public Nullable<System.DateTime> CreatedOn { get; set; }
        [Display(Name = "Created By")]
        public Nullable<int> CreatedBy { get; set; }
        [Display(Name = "Is Active")]
        public string IsActive { get; set; }
        [Display(Name = "Modified On")]
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        [Display(Name = "Modified By")]
        public Nullable<int> ModifiedBy { get; set; }

        public virtual TeachersCourseAllocation TeachersCourseAllocation { get; set; }
        public virtual TimeSlot TimeSlot { get; set; }
    }

    public class TimeSlotCourseAllocationsViewModel
    {
        public List<TimeSlotCourseAllocation> TimeSlotCourseAllocations { get; set; }
        public TimeSlotCourseAllocation SelectedTimeSlotCourseAllocation { get; set; }
        public string DisplayMode { get; set; }
    }
}
