//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampusManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableDate
    {
        public int TimeTableDateID { get; set; }
        public Nullable<System.DateTime> TimeTableDateName { get; set; }
        public string TimeTableDateDay { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    }

    public class TimeTableDateViewModel
    {
        public List<TimeTableDate> TimeTableDates { get; set; }
        public TimeTableDate SelectedTimeTableDate { get; set; }
        public string DisplayMode { get; set; }
    }
}
